### ISSUE TITLE
[Feature Request] IFF & Line drawing function on the map  

### ISSUE THREAD

**Issue by ospreyfalconbms** [UOAF/OpenRadar#2]
Excited to see new app being developed for GCI. 101 VFS is hardcore virtual squadron and we are desperately eager to have well functioned GCI app for BMS such as LotATC. 

For PvP purpose during training, having IFF codes set is very good way for ID. It would be helpful if GCI could see IFF code of each aircraft on the radar to assist with ID or killed status during the training.

It is also very helpful if GCI could have drawing-line function over the radar map, so that GCI could have better SA.

**Comment by Briland5** [comment]
Thanks for the feedback!

Drawing tools are planned, #3 

IFF information is currently not included in the BMS Tacview Real Time Stream. This means OpenRadar has no way of associating that information with contacts until someone from the BMS team adds that data into the stream.  Closing until this enhancement is possible
